### PR TITLE
No Modal Option

### PR DESCRIPTION
**Pull request by colecmc**
Added new option to show calendar without modal (‘.dp-visible’). Very
minimal style changes. Very minimal code changes. All tests still
passing.

### CODE REVIEW

**Comment by colecmc** [comment]
Use new option as follows.

`TinyDatePicker(document.querySelector('.date-example'), {
    useModal: false
});`

**Comment by chrisdavies** [comment]
Hey. Very cool. Thanks for the contribution! It seems that your editor uses different newlines than mine (or something). If you look at the diffs in GitHub, there seem to be a bunch of files that didn't actually change. Do you think you could correct that? If not, I'll pull this down locally and see if I can adjust it on my side.

**Comment by colecmc** [comment]
Yea, sure I'll have look over the weekend.

**Comment by chrisdavies** [comment]
Hey. I pulled it down and had a look, and I can just merge/tweak here, if you want.

What do you think about making the flag be called `autoHide` instead of `useModal` since it still kind of looks like a modal, it just doesn't automatically hide when you choose a date. Hm. Just a thought. 

Also, the clear button is a little strange, now, since it clears the associated input and hides the modal. But now, the modal stays up and it looks like a date is still selected. What should it do in the `useModal = false` scenario?

**Comment by colecmc** [comment]
That would be great if you could merge. Sure, feel free to use whatever name makes sense to you. The clear button should be the same as I have not modified it. I did however adjust the close button and I'm not please with how I handled it. What are your thoughts? The `useModal = false` should only remove the `dp-visible`  from the wrapper and disable the close button. Everything should still function exactly the same.

**Comment by chrisdavies** [comment]
Cool. I'll merge it in. Just out of curiosity, what's the use case that is driving this change?

**Comment by colecmc** [comment]
The requirement is to have the calendar visible (without any interaction).
I have another requirement to be highlight several specific dates.

**Comment by chrisdavies** [comment]
Ah. OK. So the idea is a screen with a calendar positioned in the static
HTML flow among other content in the UI? I think the current proposed fix
still positions the calendar absolutely (modal-looking) so it covers other
UI elements.

The multi-select is an interesting requirement. I've never really found an
approach I liked for that other than just doing date ranges (e.g. pick the
start date, pick the end date). Do you need to select a range, or do you
need to be able to select random individual dates?

**Comment by colecmc** [comment]
Yes, you're right about that. I will look at that this week, so that the calendar will position or attach itself to the specified input.

As for the other requirement I mentioned, it's from a back end event/calendar system. So there are dates which should be unavailable to the `TinyDatePicker`. As far as selection goes, the form field which your component is attached to can only accept a single date.

**Comment by chrisdavies** [comment]
Cool. OK. I'll hold off on this until you think it's ready.

**Comment by colecmc** [comment]
I didn't forget about this but I haven't had a chance to jump on it.

**Comment by chrisdavies** [comment]
Hi Cole, I decided to close this, as it's been sitting unattended for so long. Let me know if you are still actively working on it.

**Pull request closed without merging**
