### PR TITLE
add dispose method on date-range-picker

### PR DESCRIPTION
**Pull request by cameronbraid**

### CODE REVIEW

**Comment by cameronbraid** [comment]
having played with the API, it appears that there is no dispose method on tiny-date-picker

**Comment by chrisdavies** [comment]
Curious why you closed this. Did you come up with a workaround?

**Comment by cameronbraid** [comment]
when I ran my code that called the dispose method on the date range picker, I received an error saying start.dispose is not defined.  The method is actually called destroy

**Comment by chrisdavies** [comment]
Ha! I forgot that I had that in there. :)

**Comment by cameronbraid** [comment]
The date range picker doesn't need a destroy method, since it uses the date picker in permanent mode which uses dp.destroy = noop

**Pull request closed without merging**
